### PR TITLE
Add video_embed_url property for #92

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
(Untested, don't have the DB set up.)

**Comment by benabraham** [comment]
@hroncok tested and works for https://youtu.be/zmtHaZG7pPc (this is in db currently) but not for the full link https://www.youtube.com/watch?v=zmtHaZG7pPc

**Comment by hroncok** [comment]
ok, let's make it work for both

**Comment by hroncok** [comment]
```
In [1]: %paste
def video_embed_url(video_url):
    if '?' in video_url:
        _, _, query = video_url.rpartition('?')
        parts = query.split('&')
        for part in parts:
            if part.startswith('v='):
                code = part[2:]
                break
    else:
        code = video_url.rstrip('/').rpartition('/')[-1]
    return 'https://www.youtube.com/embed/' + code
## -- End pasted text --

In [2]: video_embed_url('https://www.youtube.com/watch?v=zmtHaZG7pPc&a=1')
Out[2]: 'https://www.youtube.com/embed/zmtHaZG7pPc'

In [3]: video_embed_url('https://www.youtube.com/watch?v=zmtHaZG7pPc')
Out[3]: 'https://www.youtube.com/embed/zmtHaZG7pPc'

In [4]: video_embed_url('https://www.youtube.com/watch?b=456&v=zmtHaZG7pPc')
Out[4]: 'https://www.youtube.com/embed/zmtHaZG7pPc'

In [5]: video_embed_url('https://youtu.be/zmtHaZG7pPc')
Out[5]: 'https://www.youtube.com/embed/zmtHaZG7pPc'
```

**Comment by hroncok** [comment]
This will still not work but I guess we don't need to support it:

    https://youtu.be/zmtHaZG7pPc?utm_source=4654869&utm_campain=6847869745

**Comment by starenka** [comment]
@hroncok using urllib.urlparse helps ;) anyway i have just refactored the field to contain just the video id (imo more flexible for the future) https://github.com/pyvec/cz.pycon.org-2017/commit/c0c6eefd2f504952b32cb441ab3951590adad9ec

**Comment by hroncok** [comment]
That would help, right. I wanted to keep it simple first (it didn't support
query) and then it got complicated a bit, but I just kept it as is for lack
of more energy :)

Dne 13. 9. 2017 10:34 napsal uživatel "starenka" <notifications@github.com>:

**Comment by starenka** [comment]
no prob, thanks for all the fish

**Pull request merged**
