### PR TITLE
Talk video embed, fixes #90

### LINKED ISSUE #90: Video embeds at talk detail
Last year, we froze the website and somebody requested to add links to videos there. We decided to don't do it (too much work), so I'm opening this ticket before this years website gets frozen.

The videos links should go to:

 * [Schedule](https://cz.pycon.org/2017/speakers/schedule/)
 * [Talks](https://cz.pycon.org/2017/speakers/talks/)
 * Talk detail such as [this one](https://cz.pycon.org/2017/speakers/detail/talk/1/)
 * It should be visible from the [front page](https://cz.pycon.org/2017/)
   * maybe change the *Talks* link to say *Talks + Videos*

### PR DESCRIPTION
**Pull request by benabraham**
This needs `video_url` to be in https://www.youtube.com/embed/tH1sIsH4sH format (not video url itself).

Either change for all talks or do some 🐍 magic.

### CODE REVIEW

**Comment by benabraham** [comment]
also sorry for mixing npm packages' updates, but I forgot 👴

**Comment by benabraham** [comment]
should fix #90

**Comment by hroncok** [comment]
Will add a video_embed_url property.

**Comment by hroncok** [comment]
https://github.com/pyvec/cz.pycon.org-2017/pull/93

**Comment by honzajavorek** [comment]
We could store just the video YT ID and then generate whatever link is needed.

**Comment by benabraham** [comment]
@honzajavorek We could, but this is more comfortable. Until somebody inserts a wierd URL. :) But I'd risk it as it is already done.

**Comment by benabraham** [comment]
@honzajavorek https://github.com/pyvec/cz.pycon.org-2017/pull/93#issuecomment-329097801 :D

**Pull request merged**
