### PR TITLE
draft of refused talks on waiting list

### PR DESCRIPTION
**Pull request by baradrb**

### CODE REVIEW

**Review by benabraham — COMMENTED** [review]
I think it would ease the refusal pain if you mentioned briefly talk selection process. Something explaining number of selectors and their independence and that the talk scored high, but the others just a bit more? And maybe not.

**Comment by honzajavorek** [comment]
Did we send this already?

**Comment by baradrb** [comment]
nope, sorry. change of strategy: no waiting list. if we dont have enough
speakers by the middle of May, we can hire some from the rest. but so far
we have enough.

**Comment by benabraham** [comment]
so we can close this?

**Pull request closed without merging**
